#!/usr/bin/bash
# Set screen backlight brightness for power source type.

# Usage
usage () {
  echo "${0##*/} [-a,--ac] [-b,--bat] - set screen backlight for power type."
} ; [ $# -eq 0 -o $# -gt 1 ] && usage && exit

# Root test
root_test () {
  if (( $EUID )); then
      echo "Root permissions required."
      return 1
  fi
}

source /etc/default/power-backlight.conf

case $1 in
  -a | --ac ) 
    root_test || exit 1
    for screen in /sys/class/backlight/*; do
      # brightness +1 as 0 is being counted as a value, needed to calculate
      brightmax=$(( $(<"$screen"/max_brightness) + 1 ))
      brightvar=$(( $SCREEN_BRIGHTNESS_ON_AC + 1 ))
      brightset=$(( $brightmax * $brightvar / 10 - 1 ))
      echo "$brightset" > "$screen"/brightness
    done ;;
  -b | --bat )
    root_test || exit 1
    for screen in /sys/class/backlight/*; do
      # brightness +1 as 0 is being counted as a value, needed to calculate
      brightmax=$(( $(<"$screen"/max_brightness) + 1 ))
      brightvar=$(( $SCREEN_BRIGHTNESS_ON_BAT + 1 ))
      brightset=$(( $brightmax * $brightvar / 10 - 1 ))
      echo "$brightset" > "$screen"/brightness
    done ;;
  * )
    usage && exit 1 
esac

# vim: set ft=sh ts=4 sw=4 et:
